name: CI/CD workflow

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: this is the environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from Github"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "docker container build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    if: inputs.environment == 'dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the app
      run: echo "Docker container deployed the app"
